In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [11]:
df = pd.read_csv('titanic_data_updated.csv')
df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1, inplace=True)

In [12]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [13]:
x = df.drop(['Survived'], axis=1)
x

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0     third    male  22.0      1      0   7.2500        S
1     first  female  38.0      1      0  71.2833        C
2     third  female  26.0      0      0   7.9250        S
3     first  female  35.0      1      0  53.1000        S
4     third    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886  second    male  27.0      0      0  13.0000        S
887   first  female  19.0      0      0  30.0000        S
888   third  female   NaN      1      2  23.4500        S
889   first    male  26.0      0      0  30.0000        C
890   third    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

In [14]:
y = df['Survived']
y

0       no
1      yes
2      yes
3      yes
4       no
      ...
886     no
887    yes
888     no
889    yes
890     no
Name: Survived, Length: 891, dtype: object

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [21]:
x_train

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
331   first    male  45.5      0      0   28.5000        S
733  second    male  23.0      0      0   13.0000        S
382   third    male  32.0      0      0    7.9250        S
704   third    male  26.0      1      0    7.8542        S
813   third  female   6.0      4      2   31.2750        S
..      ...     ...   ...    ...    ...       ...      ...
106   third  female  21.0      0      0    7.6500        S
270   first    male   NaN      0      0   31.0000        S
860   third    male  41.0      2      0   14.1083        S
435   first  female  14.0      1      2  120.0000        S
102   first    male  21.0      0      1   77.2875        S

[712 rows x 7 columns]

In [22]:
x_test

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
709   third    male   NaN      1      1  15.2458        C
439  second    male  31.0      0      0  10.5000        S
840   third    male  20.0      0      0   7.9250        S
720  second  female   6.0      0      1  33.0000        S
39    third  female  14.0      1      0  11.2417        C
..      ...     ...   ...    ...    ...      ...      ...
433   third    male  17.0      0      0   7.1250        S
773   third    male   NaN      0      0   7.2250        C
25    third  female  38.0      1      5  31.3875        S
84   second  female  17.0      0      0  10.5000        S
10    third  female   4.0      1      1  16.7000        S

[179 rows x 7 columns]

In [23]:
y_train

331     no
733     no
382     no
704     no
813     no
      ...
106    yes
270     no
860     no
435    yes
102     no
Name: Survived, Length: 712, dtype: object

In [24]:
y_test

709    yes
439     no
840     no
720    yes
39     yes
      ...
433     no
773     no
25     yes
84     yes
10     yes
Name: Survived, Length: 179, dtype: object

In [25]:
x

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0     third    male  22.0      1      0   7.2500        S
1     first  female  38.0      1      0  71.2833        C
2     third  female  26.0      0      0   7.9250        S
3     first  female  35.0      1      0  53.1000        S
4     third    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886  second    male  27.0      0      0  13.0000        S
887   first  female  19.0      0      0  30.0000        S
888   third  female   NaN      1      2  23.4500        S
889   first    male  26.0      0      0  30.0000        C
890   third    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

In [26]:
y

0       no
1      yes
2      yes
3      yes
4       no
      ...
886     no
887    yes
888     no
889    yes
890     no
Name: Survived, Length: 891, dtype: object