In [2]:
import numpy as np
import pandas as pd

In [6]:
lst = [10, 20, 30, 40, 50]
df = pd.DataFrame(lst)
print(df)
print(df.index)
print(type(df))

data = {
    "Name": ['md', 'nafiz', 'mahmud', 'shawon'],
    "Age": [1,2,3,4],
    "City": ['dhaka', 'savar', 'chandpur', 'noakhali']
}

new_df = pd.DataFrame(data)
display(new_df)

    0
0  10
1  20
2  30
3  40
4  50
RangeIndex(start=0, stop=5, step=1)
<class 'pandas.core.frame.DataFrame'>

     Name  Age      City
0      md    1     dhaka
1   nafiz    2     savar
2  mahmud    3  chandpur
3  shawon    4  noakhali

In [7]:
print(new_df.describe())

            Age
count  4.000000
mean   2.500000
std    1.290994
min    1.000000
25%    1.750000
50%    2.500000
75%    3.250000
max    4.000000

In [11]:
info = new_df.shape
print(f"rows: {info[0]}")
print(f"columns: {info[1]}")

columns = info[1]
print(type(columns))

rows: 4
columns: 3
<class 'int'>

In [13]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes

In [16]:
data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}
data = pd.DataFrame(data)
display(data)

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [55]:
# print(data.columns)
# print(data.index)

x = data[0:1]
# print(x)

y = data.iloc[0:4,2:3]
print(y)

   Quantity
0       100
1        60
2       200
3       150

In [56]:
data

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [62]:
data.loc[:,'Price']

0    10
1    50
2     5
3     7
Name: Price, dtype: int64

In [63]:
data.iloc[0:,1:2]

   Price
0     10
1     50
2      5
3      7

In [64]:
data

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [72]:
xxx = data.iloc[0:2,0:2]

In [73]:
xxx.shape

(2, 2)

In [74]:
employees = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma",
             "Frank", "Grace", "Henry", "Ivy", "Jack"],
    
    "Department": ["HR", "IT", "Finance", "Marketing", "IT",
                   "HR", "Finance", "Marketing", "IT", "HR"],
    
    "Salary": [45000, 60000, 55000, 50000, 65000,
               47000, 58000, 52000, 70000, 49000]
}

df = pd.DataFrame(employees)

In [75]:
df

      Name Department  Salary
0    Alice         HR   45000
1      Bob         IT   60000
2  Charlie    Finance   55000
3    David  Marketing   50000
4     Emma         IT   65000
5    Frank         HR   47000
6    Grace    Finance   58000
7    Henry  Marketing   52000
8      Ivy         IT   70000
9     Jack         HR   49000

In [76]:
df.sort_values(['Salary', 'Name'], ascending=[1,0])

      Name Department  Salary
0    Alice         HR   45000
5    Frank         HR   47000
9     Jack         HR   49000
3    David  Marketing   50000
7    Henry  Marketing   52000
2  Charlie    Finance   55000
6    Grace    Finance   58000
1      Bob         IT   60000
4     Emma         IT   65000
8      Ivy         IT   70000

In [84]:
student = {
    'Name': ['n', 'a', 'f', 'i', 'z', 'm', 'a', 'h'],
    'Score': [556,25,38,44,55,69,79,98]
}

df = pd.DataFrame(student)
df

  Name  Score
0    n    556
1    a     25
2    f     38
3    i     44
4    z     55
5    m     69
6    a     79
7    h     98

In [89]:
df.loc[(df['Score'] > 60) | (df['Score'] < 40)]

  Name  Score
0    n    556
1    a     25
2    f     38
5    m     69
6    a     79
7    h     98