In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('student-data.csv')
display(df)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [3]:
display(df.columns)

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'passed'],
      dtype='object')

In [4]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [5]:
df['school']

0      GP
1      GP
2      GP
3      GP
4      GP
       ..
390    MS
391    MS
392    MS
393    MS
394    MS
Name: school, Length: 395, dtype: object

In [6]:
display(df['school'])

0      GP
1      GP
2      GP
3      GP
4      GP
       ..
390    MS
391    MS
392    MS
393    MS
394    MS
Name: school, Length: 395, dtype: object

In [7]:
print(type(df['school']))

<class 'pandas.core.series.Series'>

In [8]:
print(df)

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... internet romantic  famrel  freetime  goout Dalc Walc health absences  \
0    ...       no       no       4         3      4    1    1      3        6
1    ...      yes       no       5         3      3    1    1      3        4
2    ...      yes       no       4         3      2    2    3      3       10
3    ...      yes      yes       3         2      2    1    1      5        2
4    ...       no       no       4         3      2    1    2      5        4
..   ...      ...      ...     ...       ...    ...  ...  ...    ...      ...
390  ...       no       no       5         5      4    4    5      4       11
391  ...      yes       no       2         4      5    3    4      2        3
392  ...       no       no       5         5      3    3    3      3        3
393  ...      yes       no       4         4      1    3    4      5        0
394  ...      yes       no       3         2      3    3    3      5        5

    passed
0       no
1       no
2      yes
3      yes
4      yes
..     ...
390     no
391    yes
392     no
393    yes
394     no

[395 rows x 31 columns]

In [9]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [10]:
display(df.head(10))

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
5,GP,M,16,U,LE3,T,4,3,services,other,...,yes,no,5,4,2,1,2,5,10,yes
6,GP,M,16,U,LE3,T,2,2,other,other,...,yes,no,4,4,4,1,1,3,0,yes
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,no,no,4,1,4,1,1,1,6,no
8,GP,M,15,U,LE3,A,3,2,services,other,...,yes,no,4,2,2,1,1,1,0,yes
9,GP,M,15,U,GT3,T,3,4,other,other,...,yes,no,5,5,1,1,1,5,0,yes

In [11]:
df.tail(2)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [12]:
df.sample(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
162,GP,M,16,U,LE3,T,1,2,other,other,...,no,no,4,4,4,2,4,5,0,no
176,GP,F,16,U,GT3,T,2,2,services,other,...,yes,no,3,4,4,1,4,5,2,yes
113,GP,M,15,U,LE3,T,4,2,teacher,other,...,yes,no,3,5,2,1,1,3,10,yes
105,GP,F,15,U,GT3,A,3,3,other,health,...,no,no,4,3,3,1,1,4,10,yes
42,GP,M,15,U,GT3,T,4,4,services,teacher,...,yes,no,4,3,3,1,1,5,2,yes

In [13]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000

In [14]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'passed'],
      dtype='object')

In [15]:
index = np.array(df.index)
print(type(index))

<class 'numpy.ndarray'>

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 31 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  passed      395 non-null    object
dtypes: int64(13), object(18)
memory usage: 95.8+ KB

In [17]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000

In [18]:
list = [['nafiz', 20], ['sami', 22], ['john', 19]]
df = pd.DataFrame(list, columns=['Name', 'Age'], index=[1,2,5])
df

    Name  Age
1  nafiz   20
2   sami   22
5   john   19

In [19]:
list = (('nafiz', 20), ('sami', 22), ('john', 19))
df = pd.DataFrame(list, columns=['Name', 'Age'], index=[1,2,5])
df

    Name  Age
1  nafiz   20
2   sami   22
5   john   19

In [20]:
# dict = {
#     'name': ['nafiz', 'sami', 'john'],
#     'age': [20, 22, 19],
#     'blood': ['A+', 'B+', 'O+']
# }
dict = [
    {'name': 'nafiz', 'age': 20, 'blood': 'A+'},
    {'name': 'sami', 'age': 22, 'blood': 'B+'},
    {'name': 'john', 'age': 19, 'blood': 'O+'}
]
df = pd.DataFrame(dict)
df

    name  age blood
0  nafiz   20    A+
1   sami   22    B+
2   john   19    O+

In [21]:
df.columns

Index(['name', 'age', 'blood'], dtype='object')

In [22]:
df['age']

0    20
1    22
2    19
Name: age, dtype: int64

In [23]:
df

    name  age blood
0  nafiz   20    A+
1   sami   22    B+
2   john   19    O+

In [24]:
df.loc[:1]

    name  age blood
0  nafiz   20    A+
1   sami   22    B+

In [25]:
df = pd.read_csv('student-data.csv')

In [26]:
df.loc[[2,4,6]]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
6,GP,M,16,U,LE3,T,2,2,other,other,...,yes,no,4,4,4,1,1,3,0,yes

In [27]:
df.loc[3:7]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
5,GP,M,16,U,LE3,T,4,3,services,other,...,yes,no,5,4,2,1,2,5,10,yes
6,GP,M,16,U,LE3,T,2,2,other,other,...,yes,no,4,4,4,1,1,3,0,yes
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,no,no,4,1,4,1,1,1,6,no

In [28]:
display(df.loc[:, ['school', 'age']])

    school  age
0       GP   18
1       GP   17
2       GP   15
3       GP   15
4       GP   16
..     ...  ...
390     MS   20
391     MS   17
392     MS   21
393     MS   18
394     MS   19

[395 rows x 2 columns]

In [29]:
display(df.loc[:, 'school':])

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [30]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [31]:
df_index = df.set_index('absences')
df_index

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,passed
absences,,,,,,,,,,,,,,,,,,,,,
6,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,yes,no,no,4,3,4,1,1,3,no
4,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,yes,no,5,3,3,1,1,3,no
10,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,yes,no,4,3,2,2,3,3,yes
2,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,yes,3,2,2,1,1,5,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,yes,no,no,4,3,2,1,2,5,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11,MS,M,20,U,LE3,A,2,2,services,services,...,yes,no,no,5,5,4,4,5,4,no
3,MS,M,17,U,LE3,T,3,1,services,services,...,yes,yes,no,2,4,5,3,4,2,yes
3,MS,M,21,R,GT3,T,1,1,other,other,...,yes,no,no,5,5,3,3,3,3,no
0,MS,M,18,R,LE3,T,3,2,services,other,...,yes,yes,no,4,4,1,3,4,5,yes
5,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,yes,no,3,2,3,3,3,5,no

In [32]:
df_index.iloc[:, 1:3]

         sex  age
absences
6          F   18
4          F   17
10         F   15
2          F   15
4          F   16
...       ..  ...
11         M   20
3          M   17
3          M   21
0          M   18
5          M   19

[395 rows x 2 columns]

In [33]:
df_index.rename(columns={'school': 'school_name', 'age': 'age_years'}, inplace=True)

In [34]:
df_index

,school_name,sex,age_years,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,passed
absences,,,,,,,,,,,,,,,,,,,,,
6,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,yes,no,no,4,3,4,1,1,3,no
4,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,yes,no,5,3,3,1,1,3,no
10,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,yes,no,4,3,2,2,3,3,yes
2,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,yes,3,2,2,1,1,5,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,yes,no,no,4,3,2,1,2,5,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11,MS,M,20,U,LE3,A,2,2,services,services,...,yes,no,no,5,5,4,4,5,4,no
3,MS,M,17,U,LE3,T,3,1,services,services,...,yes,yes,no,2,4,5,3,4,2,yes
3,MS,M,21,R,GT3,T,1,1,other,other,...,yes,no,no,5,5,3,3,3,3,no
0,MS,M,18,R,LE3,T,3,2,services,other,...,yes,yes,no,4,4,1,3,4,5,yes
5,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,yes,no,3,2,3,3,3,5,no

In [35]:
df_index.columns

Index(['school_name', 'sex', 'age_years', 'address', 'famsize', 'Pstatus',
       'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime',
       'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime',
       'goout', 'Dalc', 'Walc', 'health', 'passed'],
      dtype='object')

In [36]:
df_index.drop(labels='famsize', axis=1, inplace=True)

In [37]:
df_index.columns

Index(['school_name', 'sex', 'age_years', 'address', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'passed'],
      dtype='object')

In [38]:
df_index

,school_name,sex,age_years,address,Pstatus,Medu,Fedu,Mjob,Fjob,reason,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,passed
absences,,,,,,,,,,,,,,,,,,,,,
6,GP,F,18,U,A,4,4,at_home,teacher,course,...,yes,no,no,4,3,4,1,1,3,no
4,GP,F,17,U,T,1,1,at_home,other,course,...,yes,yes,no,5,3,3,1,1,3,no
10,GP,F,15,U,T,1,1,at_home,other,other,...,yes,yes,no,4,3,2,2,3,3,yes
2,GP,F,15,U,T,4,2,health,services,home,...,yes,yes,yes,3,2,2,1,1,5,yes
4,GP,F,16,U,T,3,3,other,other,home,...,yes,no,no,4,3,2,1,2,5,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11,MS,M,20,U,A,2,2,services,services,course,...,yes,no,no,5,5,4,4,5,4,no
3,MS,M,17,U,T,3,1,services,services,course,...,yes,yes,no,2,4,5,3,4,2,yes
3,MS,M,21,R,T,1,1,other,other,course,...,yes,no,no,5,5,3,3,3,3,no
0,MS,M,18,R,T,3,2,services,other,course,...,yes,yes,no,4,4,1,3,4,5,yes
5,MS,M,19,U,T,1,1,other,at_home,course,...,yes,yes,no,3,2,3,3,3,5,no

In [39]:
df_index.columns

Index(['school_name', 'sex', 'age_years', 'address', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'passed'],
      dtype='object')

In [40]:
df_index.loc[10, 'age_years'] = 900
display(df_index)

,school_name,sex,age_years,address,Pstatus,Medu,Fedu,Mjob,Fjob,reason,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,passed
absences,,,,,,,,,,,,,,,,,,,,,
6,GP,F,18,U,A,4,4,at_home,teacher,course,...,yes,no,no,4,3,4,1,1,3,no
4,GP,F,17,U,T,1,1,at_home,other,course,...,yes,yes,no,5,3,3,1,1,3,no
10,GP,F,900,U,T,1,1,at_home,other,other,...,yes,yes,no,4,3,2,2,3,3,yes
2,GP,F,15,U,T,4,2,health,services,home,...,yes,yes,yes,3,2,2,1,1,5,yes
4,GP,F,16,U,T,3,3,other,other,home,...,yes,no,no,4,3,2,1,2,5,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11,MS,M,20,U,A,2,2,services,services,course,...,yes,no,no,5,5,4,4,5,4,no
3,MS,M,17,U,T,3,1,services,services,course,...,yes,yes,no,2,4,5,3,4,2,yes
3,MS,M,21,R,T,1,1,other,other,course,...,yes,no,no,5,5,3,3,3,3,no
0,MS,M,18,R,T,3,2,services,other,course,...,yes,yes,no,4,4,1,3,4,5,yes
5,MS,M,19,U,T,1,1,other,at_home,course,...,yes,yes,no,3,2,3,3,3,5,no

In [41]:
print(df_index.index)

Index([ 6,  4, 10,  2,  4, 10,  0,  6,  0,  0,
       ...
        2,  7,  0,  0,  0, 11,  3,  3,  0,  5],
      dtype='int64', name='absences', length=395)

In [42]:
# for i , series in df.iterrows():
#     print(f"{i} : {series}")

In [43]:
df = pd.read_csv('sunject_number.csv')

df.sort_values(['English'], inplace=True)
df.sort_values(['English', 'Science'], inplace=True, ascending=False)
df.sort_values(['Science', 'Math'], inplace=True, ascending=[0, 1])


df

    Science  English  Math
39       95       96    94
29       94       95    93
22       93       87    91
2        92       88    90
47       92       93    91
14       91       94    92
10       90       85    88
35       90       92    89
44       89       87    88
6        89       91    95
27       88       90    87
18       87       89    86
8        86       79    84
33       86       83    85
25       85       84    82
4        84       76    81
42       83       86    84
37       82       78    80
31       81       79    77
16       80       77    83
12       78       80    76
49       78       80    79
20       77       81    79
24       76       78    74
45       76       77    75
5        75       69    72
40       74       70    73
0        74       82    78
30       73       75    70
48       73       71    72
13       71       66    69
9        70       73    67
23       70       72    68
1        69       71    65
46       68       69    67
17       68       74    71
28       67       64    66
36       66       68    64
19       65       59    63
15       64       61    58
41       63       65    61
7        62       57    60
26       61       56    59
32       60       58    62
34       59       62    57
3        58       63    54
43       58       54    56
21       57       60    55
38       55       57    53
11       52       55    49

In [44]:
df = pd.read_csv('sunject_number.csv')
df.head()

   Science  English  Math
0       74       82    78
1       69       71    65
2       92       88    90
3       58       63    54
4       84       76    81

In [45]:
eng = df.loc[df['Math'] > 90]
eng

    Science  English  Math
6        89       91    95
14       91       94    92
22       93       87    91
29       94       95    93
39       95       96    94
47       92       93    91

In [46]:
eng = df.loc[(df['Math'] < 60) & (df['Science'] > 60)]
eng

    Science  English  Math
15       64       61    58
26       61       56    59

In [47]:
df

    Science  English  Math
0        74       82    78
1        69       71    65
2        92       88    90
3        58       63    54
4        84       76    81
5        75       69    72
6        89       91    95
7        62       57    60
8        86       79    84
9        70       73    67
10       90       85    88
11       52       55    49
12       78       80    76
13       71       66    69
14       91       94    92
15       64       61    58
16       80       77    83
17       68       74    71
18       87       89    86
19       65       59    63
20       77       81    79
21       57       60    55
22       93       87    91
23       70       72    68
24       76       78    74
25       85       84    82
26       61       56    59
27       88       90    87
28       67       64    66
29       94       95    93
30       73       75    70
31       81       79    77
32       60       58    62
33       86       83    85
34       59       62    57
35       90       92    89
36       66       68    64
37       82       78    80
38       55       57    53
39       95       96    94
40       74       70    73
41       63       65    61
42       83       86    84
43       58       54    56
44       89       87    88
45       76       77    75
46       68       69    67
47       92       93    91
48       73       71    72
49       78       80    79

In [48]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Helen', 'Ian', 'Julia'],
    'Age': [24, 27, 22, 32, 29, 26, 31, 23, 28, 25],
    'Department': ['HR', 'IT', 'Finance', 'Marketing', 'IT', 'Finance', 'HR', 'Marketing', 'IT', 'Finance'],
    'Salary': [45000, 60000, 52000, 58000, 61000, 50000, 47000, 55000, 62000, 53000],
    'City': [
        'Dhaka',
        'dha Chittagong',
        'Dhaka',
        'Khulna',
        'Sylhet',
        'Dhaka',
        'Rajshahi',
        'Khulna',
        'Sylhet',
        'dHaka'
    ]
}

df = pd.DataFrame(data)
df

      Name  Age Department  Salary            City
0    Alice   24         HR   45000           Dhaka
1      Bob   27         IT   60000  dha Chittagong
2  Charlie   22    Finance   52000           Dhaka
3    David   32  Marketing   58000          Khulna
4      Eva   29         IT   61000          Sylhet
5    Frank   26    Finance   50000           Dhaka
6    Grace   31         HR   47000        Rajshahi
7    Helen   23  Marketing   55000          Khulna
8      Ian   28         IT   62000          Sylhet
9    Julia   25    Finance   53000           dHaka

In [49]:
df.loc[df['City'].str.contains('Dha')]

      Name  Age Department  Salary   City
0    Alice   24         HR   45000  Dhaka
2  Charlie   22    Finance   52000  Dhaka
5    Frank   26    Finance   50000  Dhaka

In [50]:
df.loc[df['City'].str.contains('Dha')]

      Name  Age Department  Salary   City
0    Alice   24         HR   45000  Dhaka
2  Charlie   22    Finance   52000  Dhaka
5    Frank   26    Finance   50000  Dhaka

In [51]:

df.loc[df['City'].str.contains(r"Dhaka")]

      Name  Age Department  Salary   City
0    Alice   24         HR   45000  Dhaka
2  Charlie   22    Finance   52000  Dhaka
5    Frank   26    Finance   50000  Dhaka

In [52]:
df

      Name  Age Department  Salary            City
0    Alice   24         HR   45000           Dhaka
1      Bob   27         IT   60000  dha Chittagong
2  Charlie   22    Finance   52000           Dhaka
3    David   32  Marketing   58000          Khulna
4      Eva   29         IT   61000          Sylhet
5    Frank   26    Finance   50000           Dhaka
6    Grace   31         HR   47000        Rajshahi
7    Helen   23  Marketing   55000          Khulna
8      Ian   28         IT   62000          Sylhet
9    Julia   25    Finance   53000           dHaka

In [53]:
df.loc[df['City'].str.contains(r"na$")]

    Name  Age Department  Salary    City
3  David   32  Marketing   58000  Khulna
7  Helen   23  Marketing   55000  Khulna

In [54]:
df.loc[df['Name'].str.contains(r"^[aeiou]", case=False)]

    Name  Age Department  Salary    City
0  Alice   24         HR   45000   Dhaka
4    Eva   29         IT   61000  Sylhet
8    Ian   28         IT   62000  Sylhet

In [55]:
df

      Name  Age Department  Salary            City
0    Alice   24         HR   45000           Dhaka
1      Bob   27         IT   60000  dha Chittagong
2  Charlie   22    Finance   52000           Dhaka
3    David   32  Marketing   58000          Khulna
4      Eva   29         IT   61000          Sylhet
5    Frank   26    Finance   50000           Dhaka
6    Grace   31         HR   47000        Rajshahi
7    Helen   23  Marketing   55000          Khulna
8      Ian   28         IT   62000          Sylhet
9    Julia   25    Finance   53000           dHaka

In [56]:
df.loc[df['City'].str.contains(r"Dhaka | Sylhet", case=False)]

Empty DataFrame
Columns: [Name, Age, Department, Salary, City]
Index: []

In [57]:
data = [
    {"Name": "John Smith", "Age": 35, "Address": "123 Main St, New York, NY 10001"},
    {"Name": "Jane Doe", "Age": 28, "Address": "456 Park Ave, Newark, NJ 70004"},
    {"Name": "Joe Schmo", "Age": 55, "Address": "789 Broad Way, Jersey City, NJ 07306"},
    {"Name": "Sally Smith", "Age": 42, "Address": "321 Maple St, Hoboken, NJ 07030"},
    {"Name": "Bob Johnson", "Age": 28,
        "Address": "654 Cedar Blvd, Union City, NJ 07087"},
    {"Name": "Sue Johnson", "Age": 29, "Address": "912 Oak St, Weehawken, NJ 07086"},
    {"Name": "Bill Williams", "Age": 33,
        "Address": "245 Pine Rd,West New York, NJ 07093"},
    {"Name": "Mary Johnson", "Age": 25,
        "Address": "369 Birch Ave, Guttenberg, NJ 07093"},
    {"Name": "Tom Williams", "Age": 44, "Address": "159 Willow St, Hoboken, NJ 07030"},
]

# Create the DataFrame
df = pd.DataFrame(data)

display(df)

            Name  Age                               Address
0     John Smith   35       123 Main St, New York, NY 10001
1       Jane Doe   28        456 Park Ave, Newark, NJ 70004
2      Joe Schmo   55  789 Broad Way, Jersey City, NJ 07306
3    Sally Smith   42       321 Maple St, Hoboken, NJ 07030
4    Bob Johnson   28  654 Cedar Blvd, Union City, NJ 07087
5    Sue Johnson   29       912 Oak St, Weehawken, NJ 07086
6  Bill Williams   33   245 Pine Rd,West New York, NJ 07093
7   Mary Johnson   25   369 Birch Ave, Guttenberg, NJ 07093
8   Tom Williams   44      159 Willow St, Hoboken, NJ 07030

In [58]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Helen', 'Ian', 'Julia'],
    'Age': [24, 27, 22, 32, 29, 26, 31, 23, 28, 25],
    'Department': ['HR', 'IT', 'Finance', 'Marketing', 'IT', 'Finance', 'HR', 'Marketing', 'IT', 'Finance'],
    'Salary': [45000, 60000, 52000, 58000, 61000, 50000, 47000, 55000, 62000, 53000],
    'City': [
        'Dhaka',
        'dha Chittagong',
        'Dhaka',
        'Khulna',
        'Sylhet',
        'Dhaka',
        'Rajshahi',
        'Khulna',
        'Sylhet',
        'dHaka'
    ]
}

df = pd.DataFrame(data)
df

      Name  Age Department  Salary            City
0    Alice   24         HR   45000           Dhaka
1      Bob   27         IT   60000  dha Chittagong
2  Charlie   22    Finance   52000           Dhaka
3    David   32  Marketing   58000          Khulna
4      Eva   29         IT   61000          Sylhet
5    Frank   26    Finance   50000           Dhaka
6    Grace   31         HR   47000        Rajshahi
7    Helen   23  Marketing   55000          Khulna
8      Ian   28         IT   62000          Sylhet
9    Julia   25    Finance   53000           dHaka

In [59]:
df['Jela'] = 'Noakhali'

In [60]:
df

      Name  Age Department  Salary            City      Jela
0    Alice   24         HR   45000           Dhaka  Noakhali
1      Bob   27         IT   60000  dha Chittagong  Noakhali
2  Charlie   22    Finance   52000           Dhaka  Noakhali
3    David   32  Marketing   58000          Khulna  Noakhali
4      Eva   29         IT   61000          Sylhet  Noakhali
5    Frank   26    Finance   50000           Dhaka  Noakhali
6    Grace   31         HR   47000        Rajshahi  Noakhali
7    Helen   23  Marketing   55000          Khulna  Noakhali
8      Ian   28         IT   62000          Sylhet  Noakhali
9    Julia   25    Finance   53000           dHaka  Noakhali

In [61]:
data = {
    'Name': [
        'Alice Johnson',
        'Bob',
        'Charlie Brown',
        'David Wilson',
        'Eva Taylor',
        'Frank Thomas',
        'Grace Lee',
        'Helen Clark',
        'Ian Walker',
        'Julia Adams'
    ],
    'Age': [24, 27, None, 32, 29, 26, 31, None, 28, 25],
    'Department': ['HR', 'IT', 'Finance', 'Marketing', None, 'Finance', 'HR', 'Marketing', 'IT', 'Finance'],
    'City': ['Dhaka', 'Chittagong', 'Dhaka', None, 'Sylhet', 'Dhaka', 'Rajshahi', 'Khulna', 'Sylhet', 'Dhaka'],
    'Math': [85, 72, 90, None, 88, 76, 81, 69, 95, None],
    'English': [78, 80, None, 70, 92, 74, 79, 88, None, 77],
    'Science': [92, None, 89, 68, 90, 82, None, 73, 96, 80]
}

df = pd.DataFrame(data)
df

            Name   Age Department        City  Math  English  Science
0  Alice Johnson  24.0         HR       Dhaka  85.0     78.0     92.0
1            Bob  27.0         IT  Chittagong  72.0     80.0      NaN
2  Charlie Brown   NaN    Finance       Dhaka  90.0      NaN     89.0
3   David Wilson  32.0  Marketing        None   NaN     70.0     68.0
4     Eva Taylor  29.0       None      Sylhet  88.0     92.0     90.0
5   Frank Thomas  26.0    Finance       Dhaka  76.0     74.0     82.0
6      Grace Lee  31.0         HR    Rajshahi  81.0     79.0      NaN
7    Helen Clark   NaN  Marketing      Khulna  69.0     88.0     73.0
8     Ian Walker  28.0         IT      Sylhet  95.0      NaN     96.0
9    Julia Adams  25.0    Finance       Dhaka   NaN     77.0     80.0

In [62]:
df['Total Marks'] = df['Math'] + df['English'] + df['Science']
df

,Name,Age,Department,City,Math,English,Science,Total Marks
0,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,255.0
1,Bob,27.0,IT,Chittagong,72.0,80.0,NaN,NaN
2,Charlie Brown,NaN,Finance,Dhaka,90.0,NaN,89.0,NaN
3,David Wilson,32.0,Marketing,None,NaN,70.0,68.0,NaN
4,Eva Taylor,29.0,None,Sylhet,88.0,92.0,90.0,270.0
5,Frank Thomas,26.0,Finance,Dhaka,76.0,74.0,82.0,232.0
6,Grace Lee,31.0,HR,Rajshahi,81.0,79.0,NaN,NaN
7,Helen Clark,NaN,Marketing,Khulna,69.0,88.0,73.0,230.0
8,Ian Walker,28.0,IT,Sylhet,95.0,NaN,96.0,NaN
9,Julia Adams,25.0,Finance,Dhaka,NaN,77.0,80.0,NaN

In [63]:
df

,Name,Age,Department,City,Math,English,Science,Total Marks
0,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,255.0
1,Bob,27.0,IT,Chittagong,72.0,80.0,NaN,NaN
2,Charlie Brown,NaN,Finance,Dhaka,90.0,NaN,89.0,NaN
3,David Wilson,32.0,Marketing,None,NaN,70.0,68.0,NaN
4,Eva Taylor,29.0,None,Sylhet,88.0,92.0,90.0,270.0
5,Frank Thomas,26.0,Finance,Dhaka,76.0,74.0,82.0,232.0
6,Grace Lee,31.0,HR,Rajshahi,81.0,79.0,NaN,NaN
7,Helen Clark,NaN,Marketing,Khulna,69.0,88.0,73.0,230.0
8,Ian Walker,28.0,IT,Sylhet,95.0,NaN,96.0,NaN
9,Julia Adams,25.0,Finance,Dhaka,NaN,77.0,80.0,NaN

In [64]:
df['a+ in math'] = np.where(df['Math']  > 90, 'a+', 'not a+')
df

,Name,Age,Department,City,Math,English,Science,Total Marks,a+ in math
0,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,255.0,not a+
1,Bob,27.0,IT,Chittagong,72.0,80.0,NaN,NaN,not a+
2,Charlie Brown,NaN,Finance,Dhaka,90.0,NaN,89.0,NaN,not a+
3,David Wilson,32.0,Marketing,None,NaN,70.0,68.0,NaN,not a+
4,Eva Taylor,29.0,None,Sylhet,88.0,92.0,90.0,270.0,not a+
5,Frank Thomas,26.0,Finance,Dhaka,76.0,74.0,82.0,232.0,not a+
6,Grace Lee,31.0,HR,Rajshahi,81.0,79.0,NaN,NaN,not a+
7,Helen Clark,NaN,Marketing,Khulna,69.0,88.0,73.0,230.0,not a+
8,Ian Walker,28.0,IT,Sylhet,95.0,NaN,96.0,NaN,a+
9,Julia Adams,25.0,Finance,Dhaka,NaN,77.0,80.0,NaN,not a+

In [65]:
df['first name'] = df['Name'].str.split(' ').str[0]
df

,Name,Age,Department,City,Math,English,Science,Total Marks,a+ in math,first name
0,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,255.0,not a+,Alice
1,Bob,27.0,IT,Chittagong,72.0,80.0,NaN,NaN,not a+,Bob
2,Charlie Brown,NaN,Finance,Dhaka,90.0,NaN,89.0,NaN,not a+,Charlie
3,David Wilson,32.0,Marketing,None,NaN,70.0,68.0,NaN,not a+,David
4,Eva Taylor,29.0,None,Sylhet,88.0,92.0,90.0,270.0,not a+,Eva
5,Frank Thomas,26.0,Finance,Dhaka,76.0,74.0,82.0,232.0,not a+,Frank
6,Grace Lee,31.0,HR,Rajshahi,81.0,79.0,NaN,NaN,not a+,Grace
7,Helen Clark,NaN,Marketing,Khulna,69.0,88.0,73.0,230.0,not a+,Helen
8,Ian Walker,28.0,IT,Sylhet,95.0,NaN,96.0,NaN,a+,Ian
9,Julia Adams,25.0,Finance,Dhaka,NaN,77.0,80.0,NaN,not a+,Julia

In [66]:
df.to_csv('data.csv')

In [67]:
df

,Name,Age,Department,City,Math,English,Science,Total Marks,a+ in math,first name
0,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,255.0,not a+,Alice
1,Bob,27.0,IT,Chittagong,72.0,80.0,NaN,NaN,not a+,Bob
2,Charlie Brown,NaN,Finance,Dhaka,90.0,NaN,89.0,NaN,not a+,Charlie
3,David Wilson,32.0,Marketing,None,NaN,70.0,68.0,NaN,not a+,David
4,Eva Taylor,29.0,None,Sylhet,88.0,92.0,90.0,270.0,not a+,Eva
5,Frank Thomas,26.0,Finance,Dhaka,76.0,74.0,82.0,232.0,not a+,Frank
6,Grace Lee,31.0,HR,Rajshahi,81.0,79.0,NaN,NaN,not a+,Grace
7,Helen Clark,NaN,Marketing,Khulna,69.0,88.0,73.0,230.0,not a+,Helen
8,Ian Walker,28.0,IT,Sylhet,95.0,NaN,96.0,NaN,a+,Ian
9,Julia Adams,25.0,Finance,Dhaka,NaN,77.0,80.0,NaN,not a+,Julia

In [68]:
df['Name'].unique()

array(['Alice Johnson', 'Bob', 'Charlie Brown', 'David Wilson',
       'Eva Taylor', 'Frank Thomas', 'Grace Lee', 'Helen Clark',
       'Ian Walker', 'Julia Adams'], dtype=object)

In [69]:
data = {
    'Name': [
        'Alice Johnson',
        'Bob Smith',
        'Charlie Brown',
        'Alice Johnson',
        'Eva Taylor',
        'Frank Thomas',
        'Grace Lee',
        'Bob Smith',
        'Ian Walker',
        'Julia Adams',
        'Alice Johnson',
        'Grace Lee'
    ],
    'Age': [24, 27, None, 24, 29, 26, 31, 27, 28, 25, 24, 31],
    'Department': [
        'HR', 'IT', 'Finance', 'HR', None, 'Finance',
        'HR', 'IT', 'IT', 'Finance', 'HR', 'HR'
    ],
    'City': [
        'Dhaka', 'Chittagong', 'Dhaka', 'Dhaka',
        'Sylhet', 'Dhaka', 'Rajshahi', 'Chittagong',
        'Sylhet', 'Dhaka', 'Dhaka', 'Rajshahi'
    ],
    'Math': [85, 72, 90, 85, 88, 76, 81, 72, 95, None, 85, 81],
    'English': [78, 80, None, 78, 92, 74, 79, 80, None, 77, 78, 79],
    'Science': [92, None, 89, 92, 90, 82, None, None, 96, 80, 92, None]
}

df = pd.DataFrame(data)
df

             Name   Age Department        City  Math  English  Science
0   Alice Johnson  24.0         HR       Dhaka  85.0     78.0     92.0
1       Bob Smith  27.0         IT  Chittagong  72.0     80.0      NaN
2   Charlie Brown   NaN    Finance       Dhaka  90.0      NaN     89.0
3   Alice Johnson  24.0         HR       Dhaka  85.0     78.0     92.0
4      Eva Taylor  29.0       None      Sylhet  88.0     92.0     90.0
5    Frank Thomas  26.0    Finance       Dhaka  76.0     74.0     82.0
6       Grace Lee  31.0         HR    Rajshahi  81.0     79.0      NaN
7       Bob Smith  27.0         IT  Chittagong  72.0     80.0      NaN
8      Ian Walker  28.0         IT      Sylhet  95.0      NaN     96.0
9     Julia Adams  25.0    Finance       Dhaka   NaN     77.0     80.0
10  Alice Johnson  24.0         HR       Dhaka  85.0     78.0     92.0
11      Grace Lee  31.0         HR    Rajshahi  81.0     79.0      NaN

In [70]:
df.to_csv('data.csv')

In [71]:
df['Name'].unique()

array(['Alice Johnson', 'Bob Smith', 'Charlie Brown', 'Eva Taylor',
       'Frank Thomas', 'Grace Lee', 'Ian Walker', 'Julia Adams'],
      dtype=object)

In [72]:
df.nunique()

Name          8
Age           7
Department    3
City          4
Math          7
English       6
Science       6
dtype: int64

In [73]:
df['Name'].isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
Name: Name, dtype: bool

In [74]:
df.isnull()

     Name    Age  Department   City   Math  English  Science
0   False  False       False  False  False    False    False
1   False  False       False  False  False    False     True
2   False   True       False  False  False     True    False
3   False  False       False  False  False    False    False
4   False  False        True  False  False    False    False
5   False  False       False  False  False    False    False
6   False  False       False  False  False    False     True
7   False  False       False  False  False    False     True
8   False  False       False  False  False     True    False
9   False  False       False  False   True    False    False
10  False  False       False  False  False    False    False
11  False  False       False  False  False    False     True

In [75]:
df['Age'].hasnans

True

In [85]:
print(df.duplicated())
# print(df.duplicated().sum())

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7      True
8     False
9     False
10     True
11     True
dtype: bool

In [86]:
df

             Name   Age Department        City  Math  English  Science
0   Alice Johnson  24.0         HR       Dhaka  85.0     78.0     92.0
1       Bob Smith  27.0         IT  Chittagong  72.0     80.0      NaN
2   Charlie Brown   NaN    Finance       Dhaka  90.0      NaN     89.0
3   Alice Johnson  24.0         HR       Dhaka  85.0     78.0     92.0
4      Eva Taylor  29.0       None      Sylhet  88.0     92.0     90.0
5    Frank Thomas  26.0    Finance       Dhaka  76.0     74.0     82.0
6       Grace Lee  31.0         HR    Rajshahi  81.0     79.0      NaN
7       Bob Smith  27.0         IT  Chittagong  72.0     80.0      NaN
8      Ian Walker  28.0         IT      Sylhet  95.0      NaN     96.0
9     Julia Adams  25.0    Finance       Dhaka   NaN     77.0     80.0
10  Alice Johnson  24.0         HR       Dhaka  85.0     78.0     92.0
11      Grace Lee  31.0         HR    Rajshahi  81.0     79.0      NaN

In [89]:
df.drop_duplicates(inplace=True)

In [90]:
df

            Name   Age Department        City  Math  English  Science
0  Alice Johnson  24.0         HR       Dhaka  85.0     78.0     92.0
1      Bob Smith  27.0         IT  Chittagong  72.0     80.0      NaN
2  Charlie Brown   NaN    Finance       Dhaka  90.0      NaN     89.0
4     Eva Taylor  29.0       None      Sylhet  88.0     92.0     90.0
5   Frank Thomas  26.0    Finance       Dhaka  76.0     74.0     82.0
6      Grace Lee  31.0         HR    Rajshahi  81.0     79.0      NaN
8     Ian Walker  28.0         IT      Sylhet  95.0      NaN     96.0
9    Julia Adams  25.0    Finance       Dhaka   NaN     77.0     80.0

In [94]:
df.drop_duplicates(subset=["Department"], keep='first')

            Name   Age Department        City  Math  English  Science
0  Alice Johnson  24.0         HR       Dhaka  85.0     78.0     92.0
1      Bob Smith  27.0         IT  Chittagong  72.0     80.0      NaN
2  Charlie Brown   NaN    Finance       Dhaka  90.0      NaN     89.0
4     Eva Taylor  29.0       None      Sylhet  88.0     92.0     90.0

In [95]:
df.drop_duplicates(subset=["Department"], keep='last')

          Name   Age Department      City  Math  English  Science
4   Eva Taylor  29.0       None    Sylhet  88.0     92.0     90.0
6    Grace Lee  31.0         HR  Rajshahi  81.0     79.0      NaN
8   Ian Walker  28.0         IT    Sylhet  95.0      NaN     96.0
9  Julia Adams  25.0    Finance     Dhaka   NaN     77.0     80.0

In [97]:
df.drop_duplicates(subset=["Department"], keep=False)

         Name   Age Department    City  Math  English  Science
4  Eva Taylor  29.0       None  Sylhet  88.0     92.0     90.0

In [98]:
df

            Name   Age Department        City  Math  English  Science
0  Alice Johnson  24.0         HR       Dhaka  85.0     78.0     92.0
1      Bob Smith  27.0         IT  Chittagong  72.0     80.0      NaN
2  Charlie Brown   NaN    Finance       Dhaka  90.0      NaN     89.0
4     Eva Taylor  29.0       None      Sylhet  88.0     92.0     90.0
5   Frank Thomas  26.0    Finance       Dhaka  76.0     74.0     82.0
6      Grace Lee  31.0         HR    Rajshahi  81.0     79.0      NaN
8     Ian Walker  28.0         IT      Sylhet  95.0      NaN     96.0
9    Julia Adams  25.0    Finance       Dhaka   NaN     77.0     80.0

In [112]:
df.dropna(how='all')

            Name   Age Department        City  Math  English  Science
0  Alice Johnson  24.0         HR       Dhaka  85.0     78.0     92.0
1      Bob Smith  27.0         IT  Chittagong  72.0     80.0      NaN
2  Charlie Brown   NaN    Finance       Dhaka  90.0      NaN     89.0
4     Eva Taylor  29.0       None      Sylhet  88.0     92.0     90.0
5   Frank Thomas  26.0    Finance       Dhaka  76.0     74.0     82.0
6      Grace Lee  31.0         HR    Rajshahi  81.0     79.0      NaN
8     Ian Walker  28.0         IT      Sylhet  95.0      NaN     96.0
9    Julia Adams  25.0    Finance       Dhaka   NaN     77.0     80.0

In [110]:
df

            Name   Age Department        City  Math  English  Science
0  Alice Johnson  24.0         HR       Dhaka  85.0     78.0     92.0
1      Bob Smith  27.0         IT  Chittagong  72.0     80.0      NaN
2  Charlie Brown   NaN    Finance       Dhaka  90.0      NaN     89.0
4     Eva Taylor  29.0       None      Sylhet  88.0     92.0     90.0
5   Frank Thomas  26.0    Finance       Dhaka  76.0     74.0     82.0
6      Grace Lee  31.0         HR    Rajshahi  81.0     79.0      NaN
8     Ian Walker  28.0         IT      Sylhet  95.0      NaN     96.0
9    Julia Adams  25.0    Finance       Dhaka   NaN     77.0     80.0

In [113]:
df.fillna(0)

            Name   Age Department        City  Math  English  Science
0  Alice Johnson  24.0         HR       Dhaka  85.0     78.0     92.0
1      Bob Smith  27.0         IT  Chittagong  72.0     80.0      0.0
2  Charlie Brown   0.0    Finance       Dhaka  90.0      0.0     89.0
4     Eva Taylor  29.0          0      Sylhet  88.0     92.0     90.0
5   Frank Thomas  26.0    Finance       Dhaka  76.0     74.0     82.0
6      Grace Lee  31.0         HR    Rajshahi  81.0     79.0      0.0
8     Ian Walker  28.0         IT      Sylhet  95.0      0.0     96.0
9    Julia Adams  25.0    Finance       Dhaka   0.0     77.0     80.0

In [118]:
df['Science'].fillna(df['Science'].median())

0    92.0
1    89.5
2    89.0
4    90.0
5    82.0
6    89.5
8    96.0
9    80.0
Name: Science, dtype: float64

In [122]:
print(df["Science"].sum())

529.0

In [121]:
print(df["Math"].sum())

587.0

In [123]:
print(df["Math"].mean())

83.85714285714286

In [124]:
print(df["Math"].median())

85.0

In [125]:
print(df["Math"].std())

8.071112509614592

In [128]:
df[['Science', 'Math']].corr()

          Science      Math
Science  1.000000  0.892333
Math     0.892333  1.000000

In [129]:
df[['Science', 'Math']].sum()

Science    529.0
Math       587.0
dtype: float64

In [130]:
df[['Science', 'Math']].mean()

Science    88.166667
Math       83.857143
dtype: float64

In [131]:
df[['Science', 'Math']].median()

Science    89.5
Math       85.0
dtype: float64

In [132]:
df[['Science', 'Math']].std()

Science    6.080022
Math       8.071113
dtype: float64

In [133]:
df[['Science', 'Math']].sum(axis=1)

0    177.0
1     72.0
2    179.0
4    178.0
5    158.0
6     81.0
8    191.0
9     80.0
dtype: float64

In [134]:
df

            Name   Age Department        City  Math  English  Science
0  Alice Johnson  24.0         HR       Dhaka  85.0     78.0     92.0
1      Bob Smith  27.0         IT  Chittagong  72.0     80.0      NaN
2  Charlie Brown   NaN    Finance       Dhaka  90.0      NaN     89.0
4     Eva Taylor  29.0       None      Sylhet  88.0     92.0     90.0
5   Frank Thomas  26.0    Finance       Dhaka  76.0     74.0     82.0
6      Grace Lee  31.0         HR    Rajshahi  81.0     79.0      NaN
8     Ian Walker  28.0         IT      Sylhet  95.0      NaN     96.0
9    Julia Adams  25.0    Finance       Dhaka   NaN     77.0     80.0

In [142]:
# df['Total Marks'] = df['Science']+ df['Math']
df['Total Marks'] = df.iloc[::,4:].sum(axis=1)
df

,Name,Age,Department,City,Math,English,Science,Total Marks
0,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,255.0
1,Bob Smith,27.0,IT,Chittagong,72.0,80.0,NaN,152.0
2,Charlie Brown,NaN,Finance,Dhaka,90.0,NaN,89.0,179.0
4,Eva Taylor,29.0,None,Sylhet,88.0,92.0,90.0,270.0
5,Frank Thomas,26.0,Finance,Dhaka,76.0,74.0,82.0,232.0
6,Grace Lee,31.0,HR,Rajshahi,81.0,79.0,NaN,160.0
8,Ian Walker,28.0,IT,Sylhet,95.0,NaN,96.0,191.0
9,Julia Adams,25.0,Finance,Dhaka,NaN,77.0,80.0,157.0

#

In [144]:
df

,Name,Age,Department,City,Math,English,Science,Total Marks
0,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,255.0
1,Bob Smith,27.0,IT,Chittagong,72.0,80.0,NaN,152.0
2,Charlie Brown,NaN,Finance,Dhaka,90.0,NaN,89.0,179.0
4,Eva Taylor,29.0,None,Sylhet,88.0,92.0,90.0,270.0
5,Frank Thomas,26.0,Finance,Dhaka,76.0,74.0,82.0,232.0
6,Grace Lee,31.0,HR,Rajshahi,81.0,79.0,NaN,160.0
8,Ian Walker,28.0,IT,Sylhet,95.0,NaN,96.0,191.0
9,Julia Adams,25.0,Finance,Dhaka,NaN,77.0,80.0,157.0

In [145]:
df

,Name,Age,Department,City,Math,English,Science,Total Marks
0,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,255.0
1,Bob Smith,27.0,IT,Chittagong,72.0,80.0,NaN,152.0
2,Charlie Brown,NaN,Finance,Dhaka,90.0,NaN,89.0,179.0
4,Eva Taylor,29.0,None,Sylhet,88.0,92.0,90.0,270.0
5,Frank Thomas,26.0,Finance,Dhaka,76.0,74.0,82.0,232.0
6,Grace Lee,31.0,HR,Rajshahi,81.0,79.0,NaN,160.0
8,Ian Walker,28.0,IT,Sylhet,95.0,NaN,96.0,191.0
9,Julia Adams,25.0,Finance,Dhaka,NaN,77.0,80.0,157.0

In [152]:
mx = df['Total Marks'].max()
mn = df['Total Marks'].min()
print(df['Total Marks'].sum())

1596.0

In [153]:
df['Scaled Marks'] = df["Total Marks"].apply(lambda x: (x - mn)/ (mx - mn))

In [154]:
df

,Name,Age,Department,City,Math,English,Science,Total Marks,Scaled Marks
0,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,255.0,0.872881
1,Bob Smith,27.0,IT,Chittagong,72.0,80.0,NaN,152.0,0.000000
2,Charlie Brown,NaN,Finance,Dhaka,90.0,NaN,89.0,179.0,0.228814
4,Eva Taylor,29.0,None,Sylhet,88.0,92.0,90.0,270.0,1.000000
5,Frank Thomas,26.0,Finance,Dhaka,76.0,74.0,82.0,232.0,0.677966
6,Grace Lee,31.0,HR,Rajshahi,81.0,79.0,NaN,160.0,0.067797
8,Ian Walker,28.0,IT,Sylhet,95.0,NaN,96.0,191.0,0.330508
9,Julia Adams,25.0,Finance,Dhaka,NaN,77.0,80.0,157.0,0.042373

In [155]:
def grading_system(marks):
    if marks > 200:
        return 'a+'
    elif marks > 150:
        return 'a'

df['Grades'] = df['Total Marks'].apply(grading_system)
df

,Name,Age,Department,City,Math,English,Science,Total Marks,Scaled Marks,Grades
0,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,255.0,0.872881,a+
1,Bob Smith,27.0,IT,Chittagong,72.0,80.0,NaN,152.0,0.000000,a
2,Charlie Brown,NaN,Finance,Dhaka,90.0,NaN,89.0,179.0,0.228814,a
4,Eva Taylor,29.0,None,Sylhet,88.0,92.0,90.0,270.0,1.000000,a+
5,Frank Thomas,26.0,Finance,Dhaka,76.0,74.0,82.0,232.0,0.677966,a+
6,Grace Lee,31.0,HR,Rajshahi,81.0,79.0,NaN,160.0,0.067797,a
8,Ian Walker,28.0,IT,Sylhet,95.0,NaN,96.0,191.0,0.330508,a
9,Julia Adams,25.0,Finance,Dhaka,NaN,77.0,80.0,157.0,0.042373,a

In [162]:
def marking_system(df):
    a = df['Science'] * 3
    b = df['Math'] * 4
    c = df['English'] * 5

    return a+b+c
    
    
df['Exceptional Marks'] = df.apply(marking_system, axis = 1)

In [163]:
df

,Name,Age,Department,City,Math,English,Science,Total Marks,Scaled Marks,Grades,Exceptional Marks
0,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,255.0,0.872881,a+,1006.0
1,Bob Smith,27.0,IT,Chittagong,72.0,80.0,NaN,152.0,0.000000,a,NaN
2,Charlie Brown,NaN,Finance,Dhaka,90.0,NaN,89.0,179.0,0.228814,a,NaN
4,Eva Taylor,29.0,None,Sylhet,88.0,92.0,90.0,270.0,1.000000,a+,1082.0
5,Frank Thomas,26.0,Finance,Dhaka,76.0,74.0,82.0,232.0,0.677966,a+,920.0
6,Grace Lee,31.0,HR,Rajshahi,81.0,79.0,NaN,160.0,0.067797,a,NaN
8,Ian Walker,28.0,IT,Sylhet,95.0,NaN,96.0,191.0,0.330508,a,NaN
9,Julia Adams,25.0,Finance,Dhaka,NaN,77.0,80.0,157.0,0.042373,a,NaN

In [164]:
df

,Name,Age,Department,City,Math,English,Science,Total Marks,Scaled Marks,Grades,Exceptional Marks
0,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,255.0,0.872881,a+,1006.0
1,Bob Smith,27.0,IT,Chittagong,72.0,80.0,NaN,152.0,0.000000,a,NaN
2,Charlie Brown,NaN,Finance,Dhaka,90.0,NaN,89.0,179.0,0.228814,a,NaN
4,Eva Taylor,29.0,None,Sylhet,88.0,92.0,90.0,270.0,1.000000,a+,1082.0
5,Frank Thomas,26.0,Finance,Dhaka,76.0,74.0,82.0,232.0,0.677966,a+,920.0
6,Grace Lee,31.0,HR,Rajshahi,81.0,79.0,NaN,160.0,0.067797,a,NaN
8,Ian Walker,28.0,IT,Sylhet,95.0,NaN,96.0,191.0,0.330508,a,NaN
9,Julia Adams,25.0,Finance,Dhaka,NaN,77.0,80.0,157.0,0.042373,a,NaN

In [165]:
df.describe

<bound method NDFrame.describe of             Name   Age Department        City  Math  English  Science  \
0  Alice Johnson  24.0         HR       Dhaka  85.0     78.0     92.0
1      Bob Smith  27.0         IT  Chittagong  72.0     80.0      NaN
2  Charlie Brown   NaN    Finance       Dhaka  90.0      NaN     89.0
4     Eva Taylor  29.0       None      Sylhet  88.0     92.0     90.0
5   Frank Thomas  26.0    Finance       Dhaka  76.0     74.0     82.0
6      Grace Lee  31.0         HR    Rajshahi  81.0     79.0      NaN
8     Ian Walker  28.0         IT      Sylhet  95.0      NaN     96.0
9    Julia Adams  25.0    Finance       Dhaka   NaN     77.0     80.0

   Total Marks  Scaled Marks Grades  Exceptional Marks
0        255.0      0.872881     a+             1006.0
1        152.0      0.000000      a                NaN
2        179.0      0.228814      a                NaN
4        270.0      1.000000     a+             1082.0
5        232.0      0.677966     a+              920.0
6        160.0      0.067797      a                NaN
8        191.0      0.330508      a                NaN
9        157.0      0.042373      a                NaN  >

In [166]:
df.describe()

,Age,Math,English,Science,Total Marks,Scaled Marks,Exceptional Marks
count,7.000000,7.000000,6.000000,6.000000,8.0000,8.000000,3.000000
mean,27.142857,83.857143,80.000000,88.166667,199.5000,0.402542,1002.666667
std,2.410295,8.071113,6.228965,6.080022,46.6323,0.395189,81.051424
min,24.000000,72.000000,74.000000,80.000000,152.0000,0.000000,920.000000
25%,25.500000,78.500000,77.250000,83.750000,159.2500,0.061441,963.000000
50%,27.000000,85.000000,78.500000,89.500000,185.0000,0.279661,1006.000000
75%,28.500000,89.000000,79.750000,91.500000,237.7500,0.726695,1044.000000
max,31.000000,95.000000,92.000000,96.000000,270.0000,1.000000,1082.000000

In [167]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 0 to 9
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               8 non-null      object
 1   Age                7 non-null      float64
 2   Department         7 non-null      object
 3   City               8 non-null      object
 4   Math               7 non-null      float64
 5   English            6 non-null      float64
 6   Science            6 non-null      float64
 7   Total Marks        8 non-null      float64
 8   Scaled Marks       8 non-null      float64
 9   Grades             8 non-null      object
 10  Exceptional Marks  3 non-null      float64
dtypes: float64(7), object(4)
memory usage: 768.0+ bytes

In [170]:
data = {
    'Name': [
        'Alice Johnson', 'Bob Smith', 'Charlie Brown', 'Alice Johnson',
        'Eva Taylor', 'Frank Thomas', 'Grace Lee', 'Bob Smith',
        'Ian Walker', 'Julia Adams', 'Alice Johnson', 'Grace Lee'
    ],
    'Age': [24, 27, None, 24, 29, 26, 31, 27, 28, 25, 24, 31],
    'Department': [
        'HR', 'IT', 'Finance', 'HR', None, 'Finance',
        'HR', 'IT', 'IT', 'Finance', 'HR', 'HR'
    ],
    'City': [
        'Dhaka', 'Chittagong', 'Dhaka', 'Dhaka',
        'Sylhet', 'Dhaka', 'Rajshahi', 'Chittagong',
        'Sylhet', 'Dhaka', 'Dhaka', 'Rajshahi'
    ],
    'Math': [85, 72, 90, 85, 88, 76, 81, 72, 95, None, 85, 81],
    'English': [78, 80, None, 78, 92, 74, 79, 80, None, 77, 78, 79],
    'Science': [92, None, 89, 92, 90, 82, None, None, 96, 80, 92, None],

    'Exam_Date': [
        '2026-06-01', '2026-06-01', '2026-06-02', '2026-06-02',
        '2026-06-03', '2026-06-03', '2026-06-04', '2026-06-04',
        '2026-06-05', '2026-06-05', '2026-06-06', '2026-06-06'
    ],
    'Exam_Time': [
        '10:00', '10:00', '11:30', '11:30',
        '10:00', '10:00', '14:00', '14:00',
        '09:00', '09:00', '13:00', '13:00'
    ]
}

df = pd.DataFrame(data)
df.to_csv('data.csv')

display(df)

,Name,Age,Department,City,Math,English,Science,Exam_Date,Exam_Time
0,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,2026-06-01,10:00
1,Bob Smith,27.0,IT,Chittagong,72.0,80.0,NaN,2026-06-01,10:00
2,Charlie Brown,NaN,Finance,Dhaka,90.0,NaN,89.0,2026-06-02,11:30
3,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,2026-06-02,11:30
4,Eva Taylor,29.0,None,Sylhet,88.0,92.0,90.0,2026-06-03,10:00
5,Frank Thomas,26.0,Finance,Dhaka,76.0,74.0,82.0,2026-06-03,10:00
6,Grace Lee,31.0,HR,Rajshahi,81.0,79.0,NaN,2026-06-04,14:00
7,Bob Smith,27.0,IT,Chittagong,72.0,80.0,NaN,2026-06-04,14:00
8,Ian Walker,28.0,IT,Sylhet,95.0,NaN,96.0,2026-06-05,09:00
9,Julia Adams,25.0,Finance,Dhaka,NaN,77.0,80.0,2026-06-05,09:00
10,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,2026-06-06,13:00
11,Grace Lee,31.0,HR,Rajshahi,81.0,79.0,NaN,2026-06-06,13:00

In [171]:
df.head()

,Name,Age,Department,City,Math,English,Science,Exam_Date,Exam_Time
0,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,2026-06-01,10:00
1,Bob Smith,27.0,IT,Chittagong,72.0,80.0,NaN,2026-06-01,10:00
2,Charlie Brown,NaN,Finance,Dhaka,90.0,NaN,89.0,2026-06-02,11:30
3,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,2026-06-02,11:30
4,Eva Taylor,29.0,None,Sylhet,88.0,92.0,90.0,2026-06-03,10:00

In [180]:
df['Exam Date'] = pd.to_datetime(df['Exam_Date'])

In [181]:
df['Exam Date']

0    2026-06-01
1    2026-06-01
2    2026-06-02
3    2026-06-02
4    2026-06-03
5    2026-06-03
6    2026-06-04
7    2026-06-04
8    2026-06-05
9    2026-06-05
10   2026-06-06
11   2026-06-06
Name: Exam Date, dtype: datetime64[ns]

In [183]:
df['Exam_Date'] = df['Exam Date'].dt.year

In [184]:
df['Exam_Date']

0     2026
1     2026
2     2026
3     2026
4     2026
5     2026
6     2026
7     2026
8     2026
9     2026
10    2026
11    2026
Name: Exam_Date, dtype: int32

In [186]:
df['Exam_Date'] = df['Exam Date'].dt.day
df['Exam_Date']

0     1
1     1
2     2
3     2
4     3
5     3
6     4
7     4
8     5
9     5
10    6
11    6
Name: Exam_Date, dtype: int32

In [188]:
df['Exam_Date'] = df['Exam Date'].dt.month
display(df['Exam_Date'])

0     6
1     6
2     6
3     6
4     6
5     6
6     6
7     6
8     6
9     6
10    6
11    6
Name: Exam_Date, dtype: int32

In [189]:
df

,Name,Age,Department,City,Math,English,Science,Exam_Date,Exam_Time,Exam Date,enrollment year
0,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,6,10:00,2026-06-01,2026-06-01
1,Bob Smith,27.0,IT,Chittagong,72.0,80.0,NaN,6,10:00,2026-06-01,2026-06-01
2,Charlie Brown,NaN,Finance,Dhaka,90.0,NaN,89.0,6,11:30,2026-06-02,2026-06-02
3,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,6,11:30,2026-06-02,2026-06-02
4,Eva Taylor,29.0,None,Sylhet,88.0,92.0,90.0,6,10:00,2026-06-03,2026-06-03
5,Frank Thomas,26.0,Finance,Dhaka,76.0,74.0,82.0,6,10:00,2026-06-03,2026-06-03
6,Grace Lee,31.0,HR,Rajshahi,81.0,79.0,NaN,6,14:00,2026-06-04,2026-06-04
7,Bob Smith,27.0,IT,Chittagong,72.0,80.0,NaN,6,14:00,2026-06-04,2026-06-04
8,Ian Walker,28.0,IT,Sylhet,95.0,NaN,96.0,6,09:00,2026-06-05,2026-06-05
9,Julia Adams,25.0,Finance,Dhaka,NaN,77.0,80.0,6,09:00,2026-06-05,2026-06-05
10,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,6,13:00,2026-06-06,2026-06-06
11,Grace Lee,31.0,HR,Rajshahi,81.0,79.0,NaN,6,13:00,2026-06-06,2026-06-06

In [190]:
df

,Name,Age,Department,City,Math,English,Science,Exam_Date,Exam_Time,Exam Date,enrollment year
0,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,6,10:00,2026-06-01,2026-06-01
1,Bob Smith,27.0,IT,Chittagong,72.0,80.0,NaN,6,10:00,2026-06-01,2026-06-01
2,Charlie Brown,NaN,Finance,Dhaka,90.0,NaN,89.0,6,11:30,2026-06-02,2026-06-02
3,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,6,11:30,2026-06-02,2026-06-02
4,Eva Taylor,29.0,None,Sylhet,88.0,92.0,90.0,6,10:00,2026-06-03,2026-06-03
5,Frank Thomas,26.0,Finance,Dhaka,76.0,74.0,82.0,6,10:00,2026-06-03,2026-06-03
6,Grace Lee,31.0,HR,Rajshahi,81.0,79.0,NaN,6,14:00,2026-06-04,2026-06-04
7,Bob Smith,27.0,IT,Chittagong,72.0,80.0,NaN,6,14:00,2026-06-04,2026-06-04
8,Ian Walker,28.0,IT,Sylhet,95.0,NaN,96.0,6,09:00,2026-06-05,2026-06-05
9,Julia Adams,25.0,Finance,Dhaka,NaN,77.0,80.0,6,09:00,2026-06-05,2026-06-05
10,Alice Johnson,24.0,HR,Dhaka,85.0,78.0,92.0,6,13:00,2026-06-06,2026-06-06
11,Grace Lee,31.0,HR,Rajshahi,81.0,79.0,NaN,6,13:00,2026-06-06,2026-06-06

In [219]:
data = {
    'Instructor_Name': [
        'Dr. Sarah Ahmed', 'Dr. Sarah Ahmed', 'Prof. John Miller', 'Dr. Ayesha Rahman',
        'Dr. Sarah Ahmed', 'Prof. John Miller', 'Dr. Ayesha Rahman',
        'Dr. Sarah Ahmed', 'Prof. John Miller', 'Dr. Ayesha Rahman'
    ],

    'Student_Name': [
        'Alice Johnson', 'Bob Smith', 'Charlie Brown', 'David Wilson',
        'Eva Taylor', 'Frank Thomas', 'Grace Lee',
        'Henry Walker', 'Ivy Adams', 'Jack Turner'
    ],

    'Department': [
        'CSE', 'CSE', None, 'CSE',
        'CSE', 'EEE', 'CSE',
        'CSE', 'EEE', 'CSE'
    ],

    'Math': [85, 72, 90, None, 88, 76, 81, 79, None, 84],
    'English': [78, None, 85, 70, 92, 74, None, 81, 88, 77],
    'Science': [92, 75, None, 68, 90, 82, 84, None, 95, 86]
}

df = pd.DataFrame(data)

In [220]:
df

     Instructor_Name   Student_Name Department  Math  English  Science
0    Dr. Sarah Ahmed  Alice Johnson        CSE  85.0     78.0     92.0
1    Dr. Sarah Ahmed      Bob Smith        CSE  72.0      NaN     75.0
2  Prof. John Miller  Charlie Brown       None  90.0     85.0      NaN
3  Dr. Ayesha Rahman   David Wilson        CSE   NaN     70.0     68.0
4    Dr. Sarah Ahmed     Eva Taylor        CSE  88.0     92.0     90.0
5  Prof. John Miller   Frank Thomas        EEE  76.0     74.0     82.0
6  Dr. Ayesha Rahman      Grace Lee        CSE  81.0      NaN     84.0
7    Dr. Sarah Ahmed   Henry Walker        CSE  79.0     81.0      NaN
8  Prof. John Miller      Ivy Adams        EEE   NaN     88.0     95.0
9  Dr. Ayesha Rahman    Jack Turner        CSE  84.0     77.0     86.0

In [229]:
ins_grp = df.groupby('Instructor_Name')
ins_grp
for i, j in ins_grp:
    print(i)
    display(j)

Dr. Ayesha Rahman

,Instructor_Name,Student_Name,Department,Math,English,Science,Total Marks
3,Dr. Ayesha Rahman,David Wilson,CSE,NaN,70.0,68.0,NaN
6,Dr. Ayesha Rahman,Grace Lee,CSE,81.0,NaN,84.0,NaN
9,Dr. Ayesha Rahman,Jack Turner,CSE,84.0,77.0,86.0,247.0

Dr. Sarah Ahmed

,Instructor_Name,Student_Name,Department,Math,English,Science,Total Marks
0,Dr. Sarah Ahmed,Alice Johnson,CSE,85.0,78.0,92.0,255.0
1,Dr. Sarah Ahmed,Bob Smith,CSE,72.0,NaN,75.0,NaN
4,Dr. Sarah Ahmed,Eva Taylor,CSE,88.0,92.0,90.0,270.0
7,Dr. Sarah Ahmed,Henry Walker,CSE,79.0,81.0,NaN,NaN

Prof. John Miller

,Instructor_Name,Student_Name,Department,Math,English,Science,Total Marks
2,Prof. John Miller,Charlie Brown,None,90.0,85.0,NaN,NaN
5,Prof. John Miller,Frank Thomas,EEE,76.0,74.0,82.0,232.0
8,Prof. John Miller,Ivy Adams,EEE,NaN,88.0,95.0,NaN

In [232]:
ins_grp.describe()

                   Math                                                  \
                  count  mean       std   min    25%   50%    75%   max
Instructor_Name
Dr. Ayesha Rahman   2.0  82.5  2.121320  81.0  81.75  82.5  83.25  84.0
Dr. Sarah Ahmed     4.0  81.0  7.071068  72.0  77.25  82.0  85.75  88.0
Prof. John Miller   2.0  83.0  9.899495  76.0  79.50  83.0  86.50  90.0

                  English             ... Science       Total Marks         \
                    count       mean  ...     75%   max       count   mean
Instructor_Name                       ...
Dr. Ayesha Rahman     2.0  73.500000  ...   85.00  86.0         1.0  247.0
Dr. Sarah Ahmed       3.0  83.666667  ...   91.00  92.0         2.0  262.5
Prof. John Miller     3.0  82.333333  ...   91.75  95.0         1.0  232.0


                         std    min     25%    50%     75%    max
Instructor_Name
Dr. Ayesha Rahman        NaN  247.0  247.00  247.0  247.00  247.0
Dr. Sarah Ahmed    10.606602  255.0  258.75  262.5  266.25  270.0
Prof. John Miller        NaN  232.0  232.00  232.0  232.00  232.0

[3 rows x 32 columns]

In [233]:
df

,Instructor_Name,Student_Name,Department,Math,English,Science,Total Marks
0,Dr. Sarah Ahmed,Alice Johnson,CSE,85.0,78.0,92.0,255.0
1,Dr. Sarah Ahmed,Bob Smith,CSE,72.0,NaN,75.0,NaN
2,Prof. John Miller,Charlie Brown,None,90.0,85.0,NaN,NaN
3,Dr. Ayesha Rahman,David Wilson,CSE,NaN,70.0,68.0,NaN
4,Dr. Sarah Ahmed,Eva Taylor,CSE,88.0,92.0,90.0,270.0
5,Prof. John Miller,Frank Thomas,EEE,76.0,74.0,82.0,232.0
6,Dr. Ayesha Rahman,Grace Lee,CSE,81.0,NaN,84.0,NaN
7,Dr. Sarah Ahmed,Henry Walker,CSE,79.0,81.0,NaN,NaN
8,Prof. John Miller,Ivy Adams,EEE,NaN,88.0,95.0,NaN
9,Dr. Ayesha Rahman,Jack Turner,CSE,84.0,77.0,86.0,247.0

In [234]:
df['Total Marks'] = df['Math'] + df['English'] + df['Science']

In [235]:
df

,Instructor_Name,Student_Name,Department,Math,English,Science,Total Marks
0,Dr. Sarah Ahmed,Alice Johnson,CSE,85.0,78.0,92.0,255.0
1,Dr. Sarah Ahmed,Bob Smith,CSE,72.0,NaN,75.0,NaN
2,Prof. John Miller,Charlie Brown,None,90.0,85.0,NaN,NaN
3,Dr. Ayesha Rahman,David Wilson,CSE,NaN,70.0,68.0,NaN
4,Dr. Sarah Ahmed,Eva Taylor,CSE,88.0,92.0,90.0,270.0
5,Prof. John Miller,Frank Thomas,EEE,76.0,74.0,82.0,232.0
6,Dr. Ayesha Rahman,Grace Lee,CSE,81.0,NaN,84.0,NaN
7,Dr. Sarah Ahmed,Henry Walker,CSE,79.0,81.0,NaN,NaN
8,Prof. John Miller,Ivy Adams,EEE,NaN,88.0,95.0,NaN
9,Dr. Ayesha Rahman,Jack Turner,CSE,84.0,77.0,86.0,247.0

In [236]:
ins_grp['Total Marks'].mean()

Instructor_Name
Dr. Ayesha Rahman    247.0
Dr. Sarah Ahmed      262.5
Prof. John Miller    232.0
Name: Total Marks, dtype: float64

In [237]:
ins_grp['Total Marks'].min()

Instructor_Name
Dr. Ayesha Rahman    247.0
Dr. Sarah Ahmed      255.0
Prof. John Miller    232.0
Name: Total Marks, dtype: float64

In [238]:
ins_grp['Total Marks'].max()

Instructor_Name
Dr. Ayesha Rahman    247.0
Dr. Sarah Ahmed      270.0
Prof. John Miller    232.0
Name: Total Marks, dtype: float64

In [242]:
mean_marks = ins_grp['Total Marks'].mean()
print(mean_marks)
df ['Total Marks'] = df['Total Marks'].fillna(df['Instructor_Name'].map(mean_marks))

Instructor_Name
Dr. Ayesha Rahman    247.0
Dr. Sarah Ahmed      262.5
Prof. John Miller    232.0
Name: Total Marks, dtype: float64

In [ ]:
df