In [175]:
import pandas as pd
import numpy as np

In [176]:
df = pd.read_csv('student-data.csv')
display(df)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [177]:
display(df.columns)

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'passed'],
      dtype='object')

In [178]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [179]:
df['school']

0      GP
1      GP
2      GP
3      GP
4      GP
       ..
390    MS
391    MS
392    MS
393    MS
394    MS
Name: school, Length: 395, dtype: object

In [180]:
display(df['school'])

0      GP
1      GP
2      GP
3      GP
4      GP
       ..
390    MS
391    MS
392    MS
393    MS
394    MS
Name: school, Length: 395, dtype: object

In [181]:
print(type(df['school']))

<class 'pandas.core.series.Series'>

In [182]:
print(df)

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... internet romantic  famrel  freetime  goout Dalc Walc health absences  \
0    ...       no       no       4         3      4    1    1      3        6
1    ...      yes       no       5         3      3    1    1      3        4
2    ...      yes       no       4         3      2    2    3      3       10
3    ...      yes      yes       3         2      2    1    1      5        2
4    ...       no       no       4         3      2    1    2      5        4
..   ...      ...      ...     ...       ...    ...  ...  ...    ...      ...
390  ...       no       no       5         5      4    4    5      4       11
391  ...      yes       no       2         4      5    3    4      2        3
392  ...       no       no       5         5      3    3    3      3        3
393  ...      yes       no       4         4      1    3    4      5        0
394  ...      yes       no       3         2      3    3    3      5        5

    passed
0       no
1       no
2      yes
3      yes
4      yes
..     ...
390     no
391    yes
392     no
393    yes
394     no

[395 rows x 31 columns]

In [183]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [184]:
display(df.head(10))

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
5,GP,M,16,U,LE3,T,4,3,services,other,...,yes,no,5,4,2,1,2,5,10,yes
6,GP,M,16,U,LE3,T,2,2,other,other,...,yes,no,4,4,4,1,1,3,0,yes
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,no,no,4,1,4,1,1,1,6,no
8,GP,M,15,U,LE3,A,3,2,services,other,...,yes,no,4,2,2,1,1,1,0,yes
9,GP,M,15,U,GT3,T,3,4,other,other,...,yes,no,5,5,1,1,1,5,0,yes

In [185]:
df.tail(2)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [186]:
df.sample(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
194,GP,M,16,U,GT3,T,2,3,other,other,...,yes,no,5,3,3,1,1,3,0,yes
252,GP,M,18,U,GT3,T,2,1,services,services,...,yes,no,3,2,5,2,5,5,4,no
21,GP,M,15,U,GT3,T,4,4,health,health,...,yes,no,5,4,2,1,1,5,0,yes
220,GP,F,17,R,GT3,T,2,1,at_home,services,...,yes,no,4,2,5,1,2,5,2,no
107,GP,M,16,U,GT3,T,3,3,services,other,...,yes,no,5,3,3,1,1,5,2,yes

In [187]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000

In [188]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'passed'],
      dtype='object')

In [189]:
index = np.array(df.index)
print(type(index))

<class 'numpy.ndarray'>

In [190]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 31 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  passed      395 non-null    object
dtypes: int64(13), object(18)
memory usage: 95.8+ KB

In [191]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000

In [192]:
list = [['nafiz', 20], ['sami', 22], ['john', 19]]
df = pd.DataFrame(list, columns=['Name', 'Age'], index=[1,2,5])
df

    Name  Age
1  nafiz   20
2   sami   22
5   john   19

In [193]:
list = (('nafiz', 20), ('sami', 22), ('john', 19))
df = pd.DataFrame(list, columns=['Name', 'Age'], index=[1,2,5])
df

    Name  Age
1  nafiz   20
2   sami   22
5   john   19

In [194]:
# dict = {
#     'name': ['nafiz', 'sami', 'john'],
#     'age': [20, 22, 19],
#     'blood': ['A+', 'B+', 'O+']
# }
dict = [
    {'name': 'nafiz', 'age': 20, 'blood': 'A+'},
    {'name': 'sami', 'age': 22, 'blood': 'B+'},
    {'name': 'john', 'age': 19, 'blood': 'O+'}
]
df = pd.DataFrame(dict)
df

    name  age blood
0  nafiz   20    A+
1   sami   22    B+
2   john   19    O+

In [195]:
df.columns

Index(['name', 'age', 'blood'], dtype='object')

In [196]:
df['age']

0    20
1    22
2    19
Name: age, dtype: int64

In [197]:
df

    name  age blood
0  nafiz   20    A+
1   sami   22    B+
2   john   19    O+

In [198]:
df.loc[:1]

    name  age blood
0  nafiz   20    A+
1   sami   22    B+

In [199]:
df = pd.read_csv('student-data.csv')

In [200]:
df.loc[[2,4,6]]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
6,GP,M,16,U,LE3,T,2,2,other,other,...,yes,no,4,4,4,1,1,3,0,yes

In [201]:
df.loc[3:7]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
5,GP,M,16,U,LE3,T,4,3,services,other,...,yes,no,5,4,2,1,2,5,10,yes
6,GP,M,16,U,LE3,T,2,2,other,other,...,yes,no,4,4,4,1,1,3,0,yes
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,no,no,4,1,4,1,1,1,6,no

In [202]:
display(df.loc[:, ['school', 'age']])

    school  age
0       GP   18
1       GP   17
2       GP   15
3       GP   15
4       GP   16
..     ...  ...
390     MS   20
391     MS   17
392     MS   21
393     MS   18
394     MS   19

[395 rows x 2 columns]

In [203]:
display(df.loc[:, 'school':])

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [204]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [205]:
df_index = df.set_index('absences')
df_index

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,passed
absences,,,,,,,,,,,,,,,,,,,,,
6,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,yes,no,no,4,3,4,1,1,3,no
4,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,yes,no,5,3,3,1,1,3,no
10,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,yes,no,4,3,2,2,3,3,yes
2,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,yes,3,2,2,1,1,5,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,yes,no,no,4,3,2,1,2,5,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11,MS,M,20,U,LE3,A,2,2,services,services,...,yes,no,no,5,5,4,4,5,4,no
3,MS,M,17,U,LE3,T,3,1,services,services,...,yes,yes,no,2,4,5,3,4,2,yes
3,MS,M,21,R,GT3,T,1,1,other,other,...,yes,no,no,5,5,3,3,3,3,no
0,MS,M,18,R,LE3,T,3,2,services,other,...,yes,yes,no,4,4,1,3,4,5,yes
5,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,yes,no,3,2,3,3,3,5,no

In [206]:
df_index.iloc[:, 1:3]

         sex  age
absences
6          F   18
4          F   17
10         F   15
2          F   15
4          F   16
...       ..  ...
11         M   20
3          M   17
3          M   21
0          M   18
5          M   19

[395 rows x 2 columns]

In [207]:
df_index.rename(columns={'school': 'school_name', 'age': 'age_years'}, inplace=True)

In [208]:
df_index

,school_name,sex,age_years,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,passed
absences,,,,,,,,,,,,,,,,,,,,,
6,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,yes,no,no,4,3,4,1,1,3,no
4,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,yes,no,5,3,3,1,1,3,no
10,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,yes,no,4,3,2,2,3,3,yes
2,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,yes,3,2,2,1,1,5,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,yes,no,no,4,3,2,1,2,5,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11,MS,M,20,U,LE3,A,2,2,services,services,...,yes,no,no,5,5,4,4,5,4,no
3,MS,M,17,U,LE3,T,3,1,services,services,...,yes,yes,no,2,4,5,3,4,2,yes
3,MS,M,21,R,GT3,T,1,1,other,other,...,yes,no,no,5,5,3,3,3,3,no
0,MS,M,18,R,LE3,T,3,2,services,other,...,yes,yes,no,4,4,1,3,4,5,yes
5,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,yes,no,3,2,3,3,3,5,no

In [209]:
df_index.columns

Index(['school_name', 'sex', 'age_years', 'address', 'famsize', 'Pstatus',
       'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime',
       'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime',
       'goout', 'Dalc', 'Walc', 'health', 'passed'],
      dtype='object')

In [210]:
df_index.drop(labels='famsize', axis=1, inplace=True)

In [211]:
df_index.columns

Index(['school_name', 'sex', 'age_years', 'address', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'passed'],
      dtype='object')

In [212]:
df_index

,school_name,sex,age_years,address,Pstatus,Medu,Fedu,Mjob,Fjob,reason,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,passed
absences,,,,,,,,,,,,,,,,,,,,,
6,GP,F,18,U,A,4,4,at_home,teacher,course,...,yes,no,no,4,3,4,1,1,3,no
4,GP,F,17,U,T,1,1,at_home,other,course,...,yes,yes,no,5,3,3,1,1,3,no
10,GP,F,15,U,T,1,1,at_home,other,other,...,yes,yes,no,4,3,2,2,3,3,yes
2,GP,F,15,U,T,4,2,health,services,home,...,yes,yes,yes,3,2,2,1,1,5,yes
4,GP,F,16,U,T,3,3,other,other,home,...,yes,no,no,4,3,2,1,2,5,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11,MS,M,20,U,A,2,2,services,services,course,...,yes,no,no,5,5,4,4,5,4,no
3,MS,M,17,U,T,3,1,services,services,course,...,yes,yes,no,2,4,5,3,4,2,yes
3,MS,M,21,R,T,1,1,other,other,course,...,yes,no,no,5,5,3,3,3,3,no
0,MS,M,18,R,T,3,2,services,other,course,...,yes,yes,no,4,4,1,3,4,5,yes
5,MS,M,19,U,T,1,1,other,at_home,course,...,yes,yes,no,3,2,3,3,3,5,no

In [213]:
df_index.columns

Index(['school_name', 'sex', 'age_years', 'address', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'passed'],
      dtype='object')

In [214]:
df_index.loc[10, 'age_years'] = 900
display(df_index)

,school_name,sex,age_years,address,Pstatus,Medu,Fedu,Mjob,Fjob,reason,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,passed
absences,,,,,,,,,,,,,,,,,,,,,
6,GP,F,18,U,A,4,4,at_home,teacher,course,...,yes,no,no,4,3,4,1,1,3,no
4,GP,F,17,U,T,1,1,at_home,other,course,...,yes,yes,no,5,3,3,1,1,3,no
10,GP,F,900,U,T,1,1,at_home,other,other,...,yes,yes,no,4,3,2,2,3,3,yes
2,GP,F,15,U,T,4,2,health,services,home,...,yes,yes,yes,3,2,2,1,1,5,yes
4,GP,F,16,U,T,3,3,other,other,home,...,yes,no,no,4,3,2,1,2,5,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11,MS,M,20,U,A,2,2,services,services,course,...,yes,no,no,5,5,4,4,5,4,no
3,MS,M,17,U,T,3,1,services,services,course,...,yes,yes,no,2,4,5,3,4,2,yes
3,MS,M,21,R,T,1,1,other,other,course,...,yes,no,no,5,5,3,3,3,3,no
0,MS,M,18,R,T,3,2,services,other,course,...,yes,yes,no,4,4,1,3,4,5,yes
5,MS,M,19,U,T,1,1,other,at_home,course,...,yes,yes,no,3,2,3,3,3,5,no

In [215]:
print(df_index.index)

Index([ 6,  4, 10,  2,  4, 10,  0,  6,  0,  0,
       ...
        2,  7,  0,  0,  0, 11,  3,  3,  0,  5],
      dtype='int64', name='absences', length=395)

In [216]:
# for i , series in df.iterrows():
#     print(f"{i} : {series}")

In [232]:
df = pd.read_csv('sunject_number.csv')

df.sort_values(['English'], inplace=True)
df.sort_values(['English', 'Science'], inplace=True, ascending=False)
df.sort_values(['Science', 'Math'], inplace=True, ascending=[0, 1])


df

    Science  English  Math
39       95       96    94
29       94       95    93
22       93       87    91
2        92       88    90
47       92       93    91
14       91       94    92
10       90       85    88
35       90       92    89
44       89       87    88
6        89       91    95
27       88       90    87
18       87       89    86
8        86       79    84
33       86       83    85
25       85       84    82
4        84       76    81
42       83       86    84
37       82       78    80
31       81       79    77
16       80       77    83
12       78       80    76
49       78       80    79
20       77       81    79
24       76       78    74
45       76       77    75
5        75       69    72
40       74       70    73
0        74       82    78
30       73       75    70
48       73       71    72
13       71       66    69
9        70       73    67
23       70       72    68
1        69       71    65
46       68       69    67
17       68       74    71
28       67       64    66
36       66       68    64
19       65       59    63
15       64       61    58
41       63       65    61
7        62       57    60
26       61       56    59
32       60       58    62
34       59       62    57
3        58       63    54
43       58       54    56
21       57       60    55
38       55       57    53
11       52       55    49

In [235]:
df = pd.read_csv('sunject_number.csv')
df.head()

   Science  English  Math
0       74       82    78
1       69       71    65
2       92       88    90
3       58       63    54
4       84       76    81

In [237]:
eng = df.loc[df['Math'] > 90]
eng

    Science  English  Math
6        89       91    95
14       91       94    92
22       93       87    91
29       94       95    93
39       95       96    94
47       92       93    91

In [242]:
eng = df.loc[(df['Math'] < 60) & (df['Science'] > 60)]
eng

    Science  English  Math
15       64       61    58
26       61       56    59