In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('student-data.csv')
display(df)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [4]:
display(df.columns)

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'passed'],
      dtype='object')

In [5]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [6]:
df['school']

0      GP
1      GP
2      GP
3      GP
4      GP
       ..
390    MS
391    MS
392    MS
393    MS
394    MS
Name: school, Length: 395, dtype: object

In [7]:
display(df['school'])

0      GP
1      GP
2      GP
3      GP
4      GP
       ..
390    MS
391    MS
392    MS
393    MS
394    MS
Name: school, Length: 395, dtype: object

In [8]:
print(type(df['school']))

<class 'pandas.core.series.Series'>

In [9]:
print(df)

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... internet romantic  famrel  freetime  goout Dalc Walc health absences  \
0    ...       no       no       4         3      4    1    1      3        6
1    ...      yes       no       5         3      3    1    1      3        4
2    ...      yes       no       4         3      2    2    3      3       10
3    ...      yes      yes       3         2      2    1    1      5        2
4    ...       no       no       4         3      2    1    2      5        4
..   ...      ...      ...     ...       ...    ...  ...  ...    ...      ...
390  ...       no       no       5         5      4    4    5      4       11
391  ...      yes       no       2         4      5    3    4      2        3
392  ...       no       no       5         5      3    3    3      3        3
393  ...      yes       no       4         4      1    3    4      5        0
394  ...      yes       no       3         2      3    3    3      5        5

    passed
0       no
1       no
2      yes
3      yes
4      yes
..     ...
390     no
391    yes
392     no
393    yes
394     no

[395 rows x 31 columns]

In [10]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [11]:
display(df.head(10))

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
5,GP,M,16,U,LE3,T,4,3,services,other,...,yes,no,5,4,2,1,2,5,10,yes
6,GP,M,16,U,LE3,T,2,2,other,other,...,yes,no,4,4,4,1,1,3,0,yes
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,no,no,4,1,4,1,1,1,6,no
8,GP,M,15,U,LE3,A,3,2,services,other,...,yes,no,4,2,2,1,1,1,0,yes
9,GP,M,15,U,GT3,T,3,4,other,other,...,yes,no,5,5,1,1,1,5,0,yes

In [12]:
df.tail(20)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
375,MS,F,18,R,GT3,T,1,1,other,other,...,yes,no,4,3,2,1,2,4,2,yes
376,MS,F,20,U,GT3,T,4,2,health,other,...,yes,yes,5,4,3,1,1,3,4,yes
377,MS,F,18,R,LE3,T,4,4,teacher,services,...,yes,no,5,4,3,3,4,2,4,yes
378,MS,F,18,U,GT3,T,3,3,other,other,...,yes,yes,4,1,3,1,2,1,0,yes
379,MS,F,17,R,GT3,T,3,1,at_home,other,...,yes,no,4,5,4,2,3,1,17,yes
380,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,yes,no,3,2,4,1,4,2,4,yes
381,MS,M,18,R,GT3,T,2,1,other,other,...,yes,yes,4,4,3,1,3,5,5,no
382,MS,M,17,U,GT3,T,2,3,other,services,...,yes,no,4,4,3,1,1,3,2,yes
383,MS,M,19,R,GT3,T,1,1,other,services,...,no,no,4,3,2,1,3,5,0,no
384,MS,M,18,R,GT3,T,4,2,other,other,...,no,no,5,4,3,4,3,3,14,no
385,MS,F,18,R,GT3,T,2,2,at_home,other,...,no,no,5,3,3,1,3,4,2,yes
386,MS,F,18,R,GT3,T,4,4,teacher,at_home,...,yes,yes,4,4,3,2,2,5,7,no
387,MS,F,19,R,GT3,T,2,3,services,other,...,yes,no,5,4,2,1,2,5,0,no
388,MS,F,18,U,LE3,T,3,1,teacher,services,...,yes,no,4,3,4,1,1,1,0,no
389,MS,F,18,U,GT3,T,1,1,other,other,...,no,no,1,1,1,1,1,5,0,no
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [13]:
df.sample(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
64,GP,F,15,U,LE3,T,4,3,services,services,...,yes,yes,4,4,4,2,4,2,0,yes
15,GP,F,16,U,GT3,T,4,4,health,other,...,yes,no,4,4,4,1,2,2,4,yes
146,GP,F,15,U,GT3,T,3,2,health,services,...,yes,no,3,3,2,1,1,3,0,no
170,GP,M,16,U,GT3,T,3,4,other,other,...,yes,no,3,4,5,2,4,2,0,no
61,GP,F,16,U,GT3,T,1,1,services,services,...,yes,yes,5,5,5,5,5,5,6,yes